### ISSUE TITLE
Many bugs

### ISSUE THREAD

**Issue by mzch** [BanzaiTokyo/askapp#73]
- Python: 3.8.5
- OS: Debian 10.5

1. `pagination_bootstrap` is wrong name.
```diff
--- settings.py.bak	2020-09-24 16:56:58.473943519 +0900
+++ settings.py	2020-09-24 17:58:41.584376818 +0900
@@ -56,7 +56,7 @@
     'django_countries',
     'rules_light',
     'mptt',
-    'pagination_bootstrap',
+    'django_pagination_bootstrap',
     'markdownx',
     'memoize',
     'registration'
@@ -71,7 +71,7 @@
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'rules_light.middleware.Middleware',
-    'pagination_bootstrap.middleware.PaginationMiddleware',
+    'django_pagination_bootstrap.middleware.PaginationMiddleware',
     'askapp.middleware.WhodidMiddleware',

 )
```

2. `python_2_unicode_compatible` is in `six`
```diff
--- models.py.bak	2020-09-24 17:39:34.759515802 +0900
+++ models.py	2020-09-24 17:42:06.696675611 +0900
@@ -1,7 +1,7 @@
 from django.db import models
 from django.db.utils import IntegrityError
 from django.utils.translation import ugettext_lazy as _
-from django.utils.encoding import python_2_unicode_compatible
+from six import python_2_unicode_compatible


 @python_2_unicode_compatible
```
3. `curry` is removed from Django 3.0
```diff
--- middleware.py.bak	2020-09-24 18:35:35.045879562 +0900
+++ middleware.py	2020-09-24 18:17:25.925353250 +0900
@@ -7,7 +7,7 @@
     pass

 from django.db.models import signals
-from django.utils.functional import curry
+from functools import partial


 class WhodidMiddleware(object):
@@ -18,7 +18,7 @@
             else:
                 user = None

-            mark_whodid = curry(self.mark_whodid, user)
+            mark_whodid = partial(self.mark_whodid, user)
             signals.pre_save.connect(mark_whodid,  dispatch_uid = (self.__class__, request,), weak = False)

     def process_response(self, request, response):
```

~~4. Internal Server Error.~~
EDITED: This was my config issue, sorry.

**Comment by BanzaiTokyo** [comment]
@mzch Thank you for your comment! We have not adapted AskApp for Django 3, but we are planning to. Please, continue posting suggestions for improvements, we'll take them into account when working on updates.

**Comment by mzch** [comment]
Thanks. When I added `Django<3.0` to `requirements.txt`, these issues are fixed.
But next, I went to my site top, then showed `'NoneType' object has no attribute 'get'` as below:

<img width="1283" alt="ScreeShot" src="https://user-images.githubusercontent.com/621178/94158284-30d8a580-febd-11ea-98a5-4289d86ac293.png">

Could anyone tell me how to fix it?

**Comment by BanzaiTokyo** [comment]
@mzch sure, we'll help you fix it. Could you please, get in touch with me at banzaitokyo@gmail.com ? I tried writing to the address in your profile, but it doesn't seem to be working.

**Comment by toxa23** [comment]
@mzch I froze all package versions, please pull the changes and reinstall the packages by `pip install --upgrade -r requirements.txt`

**Comment by mzch** [comment]
I did, and start app but the following error occurred:
```
[2020-09-25 09:58:06 +0200] [1579] [INFO] Starting gunicorn 20.0.4
[2020-09-25 09:58:06 +0200] [1579] [INFO] Listening at: http://127.0.0.1:9990 (1579)
[2020-09-25 09:58:06 +0200] [1579] [INFO] Using worker: threads
[2020-09-25 09:58:06 +0200] [1727] [INFO] Booting worker with pid: 1727
[2020-09-25 09:58:06 +0200] [1728] [INFO] Booting worker with pid: 1728
[2020-09-25 07:58:07 +0000] [1728] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/askapp/askapp/askapp/wsgi.py", line 37, in <module>
    application = get_wsgi_application()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/conf/__init__.py", line 176, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[2020-09-25 07:58:07 +0000] [1728] [INFO] Worker exiting (pid: 1728)
[2020-09-25 07:58:07 +0000] [1727] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/askapp/askapp/askapp/wsgi.py", line 37, in <module>
    application = get_wsgi_application()
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/askapp/.pyenv/versions/3.6.12/lib/python3.6/site-packages/django/conf/__init__.py", line 176, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[2020-09-25 07:58:07 +0000] [1727] [INFO] Worker exiting (pid: 1727)
[2020-09-25 09:58:07 +0200] [1579] [INFO] Shutting down: Master
[2020-09-25 09:58:07 +0200] [1579] [INFO] Reason: Worker failed to boot.
```
- .env
```sh
DJANGO_SECRET=secret
DB_HOST=127.0.0.1
DB_DATABASE=askapp
DB_USER=askapp
DB_PASSWORD=password
EMAIL_HOST=mx1.mail-services.net
EMAIL_FROM_ADDRESS=no-reply@usersvoice.net
EMAIL_ADDRESS=admin@example.com
EMAIL_HOST_PASSWORD=password
GOOGLE_API_KEY=apikey
RECAPTCHA_PUBLIC_KEY=publickey
RECAPTCHA_PRIVATE_KEY=privatekey
SITE_NAME="User's Voice"
```

**Comment by toxa23** [comment]
@mzch is your .env file located in /srv/askapp/askapp/ folder?

**Comment by mzch** [comment]
@toxa23 Yes.

**Comment by mzch** [comment]
p.s.
the latest `requirements.txt` has no entry of `six`

**Comment by mzch** [comment]
I put `SECRET_KEY` value in `settings.py` directly but the same error was reported.

**Comment by mzch** [comment]
Trying `python manage.py runserver`, it runs successfully. But `gunicorn` fails.

**Comment by toxa23** [comment]
We did not test the project with `gunicorn`. Need some time to investigate the issue.

**Comment by mzch** [comment]
OK, please. But do you use mod_wsgi?

**Comment by toxa23** [comment]
Yes, we are.
We do have `WSGIScriptAlias / '<whatever>/askapp/wsgi.py'` config setting

**Comment by mzch** [comment]
Mm...I tried `mod_wsgi` but the same error happened. What's wrong...?

- apache.conf

```apache
WSGIPythonHome /srv/askapp/.pyenv/versions/3.8.5
WSGIPythonPath /srv/askapp/askapp

<VirtualHost *:80>
	ServerName usersvoice.net
	ServerAlias www.usersvoice.net
	RewriteEngine On
	RewriteCond %{SERVER_NAME} =www.usersvoice.net [OR]
	RewriteCond %{SERVER_NAME} =usersvoice.net
	RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>

	ServerName usersvoice.net
	ServerAlias www.usersvoice.net
	ServerAdmin webmaster@usersvoice.net

	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLCertificateFile /etc/letsencrypt/live/usersvoice.net/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/usersvoice.net/privkey.pem

	RewriteEngine On
	RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
	RewriteRule ^(.*)$ https://%1$1 [R=301,L]

	WSGIDaemonProcess askapp user=askapp group=askapp processes=2 threads=4
	WSGIProcessGroup askapp

	Alias /static/ /srv/askapp/askapp/askapp/static/
	<Directory "/srv/askapp/askapp/askapp/static">
		Require all granted
	</Directory>

	WSGIScriptAlias / /srv/askapp/askapp/askapp/wsgi.py
	<Directory "/srv/askapp/askapp/askapp">
		<Files "wsgi.py">
			Require all granted
		</Files>
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
</IfModule>
```

- apache.log
```
[Fri Sep 25 10:28:39.931635 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682] mod_wsgi (pid=14610): Failed to exec Python script file '/srv/askapp/askapp/askapp/wsgi.py'.
[Fri Sep 25 10:28:39.931728 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682] mod_wsgi (pid=14610): Exception occurred processing WSGI script '/srv/askapp/askapp/askapp/wsgi.py'.
[Fri Sep 25 10:28:39.932352 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682] Traceback (most recent call last):
[Fri Sep 25 10:28:39.932409 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]   File "/srv/askapp/askapp/askapp/wsgi.py", line 37, in <module>
[Fri Sep 25 10:28:39.932433 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]     application = get_wsgi_application()
[Fri Sep 25 10:28:39.932443 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]   File "/srv/askapp/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Fri Sep 25 10:28:39.932448 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]     django.setup(set_prefix=False)
[Fri Sep 25 10:28:39.932456 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]   File "/srv/askapp/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
[Fri Sep 25 10:28:39.932461 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Sep 25 10:28:39.932469 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]   File "/srv/askapp/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
[Fri Sep 25 10:28:39.932474 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]     self._setup(name)
[Fri Sep 25 10:28:39.932482 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]   File "/srv/askapp/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
[Fri Sep 25 10:28:39.932487 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]     self._wrapped = Settings(settings_module)
[Fri Sep 25 10:28:39.932495 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]   File "/srv/askapp/.pyenv/versions/3.8.5/lib/python3.8/site-packages/django/conf/__init__.py", line 176, in __init__
[Fri Sep 25 10:28:39.932513 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682]     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
[Fri Sep 25 10:28:39.932536 2020] [wsgi:error] [pid 14610:tid 140500353730304] [remote 2405:6584:7840:f00:1cdb:38eb:21b:1ec7:52682] django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

**Comment by toxa23** [comment]
Please try
```
<Directory "/srv/askapp/askapp/askapp">
	Require all granted
</Directory>
```
without `<Files>`

**Comment by mzch** [comment]
I tried but same...

**Comment by toxa23** [comment]
Pushed a commit to fix /accounts/register/ page

**Comment by mzch** [comment]
I found `askapp/views.py` is modified. But the same error is reported.

**Comment by mzch** [comment]
`django/conf/__init__.py` is called twice. At the first time SECRET_KEY is set, but at the second time it is empty.
